name: .NET CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # OJO: Si es 1, GitVersion no puede calcular la versión

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v1

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Aquí usamos la salida del JSON que acabas de ver en tu terminal
      - name: Build
        run: dotnet build /p:Version=${{ steps.gitversion.outputs.SemVer }}

      - name: Test
        run: dotnet test --no-build